# coding: utf-8

"""
    databus-server

    databus-server APIs  # noqa: E501

    The version of the OpenAPI document: 0.99.0
    Generated by: https://openapi-generator.tech
"""

from databus_client.paths.databus.get import DatabusHome


class CrateApi(
    DatabusHome,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
