# coding: utf-8

"""
    databus-server

    databus-server APIs  # noqa: E501

    The version of the OpenAPI document: 0.99.0
    Generated by: https://openapi-generator.tech
"""

from databus_client.paths.databus_dao_get_ai_datasheet_ids_ai_id.get import DaoGetAiDatasheetIds
from databus_client.paths.databus_dao_get_ai_ai_id.get import DaoGetAiPo
from databus_client.paths.databus_dao_get_revision_datasheet_id.get import DaoGetRevision


class DataDaoApiApi(
    DaoGetAiDatasheetIds,
    DaoGetAiPo,
    DaoGetRevision,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
