import { t, Strings } from '@apitable/core';

export const strings = {
  // Block-level elements
  paragraph: t(Strings.paragraph),
  heading1: t(Strings.heading_one),
  heading2: t(Strings.heading_two),
  heading3: t(Strings.heading_three),
  heading4: t(Strings.heading_four),
  heading5: t(Strings.heading_five),
  heading6: t(Strings.heading_six),
  image: t(Strings.image),
  orderedList: t(Strings.ordered_list),
  bulletList: t(Strings.unordered_list),
  taskList: t(Strings.task_list),
  blockquote: t(Strings.quote),
  codeBlock: t(Strings.code_block),
  divider: t(Strings.divider),
  table: t(Strings.table),
  // Inline elements
  link: t(Strings.link),
  italic: t(Strings.italic),
  underline: t(Strings.under_line),
  strike: t(Strings.strikethrough),
  bold: t(Strings.bold),
  code: t(Strings.inline_code),
  mention: t(Strings.mention),
  highlight: t(Strings.highlight),
  // Alignment method
  left: t(Strings.align_left),
  center: t(Strings.align_center),
  right: t(Strings.align_right),
  // Other
  ok: t(Strings.submit),
  cancel: t(Strings.cancel),
  text: t(Strings.text),
  edit: t(Strings.edit),
  unlink: t(Strings.unlink),
  placeholder: t(Strings.editor_placeholder),
  commonFormat: t(Strings.common_format),
  insertBelow: t(Strings.insert_below),
  insertAbove: t(Strings.insert_above),
  mediaElement: t(Strings.media_element),
  associatedElement: t(Strings.associated_element),
  addImage: t(Strings.add_image),
  imageSizeError: t(Strings.image_limit, { number: 2 }),
  imageTypeError: t(Strings.support_image_formats),
  imageUploading: t(Strings.image_uploading),
  copySuccess: t(Strings.copy_success),
  copyFailed: t(Strings.copy_failed),
  delete: t(Strings.delete),
  visit: t(Strings.visit),
  linkInputPlaceholder: t(Strings.link_input_placeholder),
  video: t(Strings.video),
};
