-- APITable <https://github.com/apitable/apitable>
-- Copyright (C) 2022 APITable Ltd. <https://apitable.com>
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU Affero General Public License for more details.
--
-- You should have received a copy of the GNU Affero General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.

CREATE TABLE `${table.prefix}wechat_mp_qrcode`
(
    `id`             bigint(20) unsigned                                          NOT NULL COMMENT 'Primary Key',
    `app_id`         varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci          DEFAULT NULL COMMENT 'Application ID',
    `type`           varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Type Value(Temporary:QR_SCENE、QR_STR_SCENE;Permanent:QR_LIMIT_SCENE、QR_LIMIT_STR_SCENE)',
    `scene`          varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci          DEFAULT NULL COMMENT 'Scene Values',
    `ticket`         varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci         DEFAULT NULL COMMENT 'QR code ticket, which can be exchanged for QR code within the valid time',
    `expire_seconds` int(10)                                                               DEFAULT NULL COMMENT 'Valid time of QR code (unit: second, -1 means permanent)',
    `url`            varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci         DEFAULT NULL COMMENT 'The address of the QR code image after parsing, and the image can be generated by yourself',
    `is_deleted`     tinyint(1) unsigned                                          NOT NULL DEFAULT '0' COMMENT 'Delete Tag (0: No, 1: Yes)',
    `created_by`     bigint(20)                                                            DEFAULT NULL COMMENT 'Creator',
    `updated_by`     bigint(20)                                                            DEFAULT NULL COMMENT 'Last Update By',
    `created_at`     timestamp                                                    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create Time',
    `updated_at`     timestamp                                                    NULL     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update Time',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT ='Third Party System - WeChat Mp Qrcode Table';
