/**
 * databus-server
 * databus-server APIs
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentRO { 
    data: number[];
    document_type: number;
    props?: string | null;
    resource_id: string;
    space_id: string;
    title?: string | null;
    updated_by?: string | null;
}

